### ISSUE TITLE
[Help] How would you put all files from a directory in a list?

### ISSUE THREAD

**Issue by VtheRtech** [elipousson/sharepointr#11]
hello I was wondering if something like this was possible with your package: 

```R
  # Get a list of all xlsx files in the specified directory
  file_paths <- list.files(
    path = here::here("data"),
    pattern = "\\.xlsx$",
    full.names = TRUE
```
This snippet grabs all the files in a directory & indexs them in a list. I can add more to the script if its not obvious what it does.

**Comment by elipousson** [comment]
The sp_dir_ls function is probably the closest equivalent if you don’t want to download the files first: https://elipousson.github.io/sharepointr/reference/sp_dir_info.html

The recursive functionality for sp_dir_info is pretty slow but it works most of the time.

If you run into any bugs or unexpected behavior, I please let me know!

**Comment by VtheRtech** [comment]
can you provide a quick example? 

I keep gettting the following message:

``sharepointr::sp_dir_list(tt)``
"Loading Microsoft Graph Login for default tenant"

Im using a link to goes directly to a directory.

**Comment by elipousson** [comment]
That message should launch a browser window where you can authenticate the application. There are a few links related to the authorization flow on the README but I’ve been meaning to add some notes on the edge cases.

**Comment by elipousson** [comment]
If you haven't talked to your system administrator already, you may need to get the Microsof365 app ID allow listed. That app ID and the permissions required are included in the {Microsoft365} [documentation on app registration](https://github.com/Azure/Microsoft365R/blob/master/inst/app_registration.md).

Once you have the permissions worked out, here is the process I'd recommend for trouble-shooting: start by passing the URL to the [get_sp_site](https://elipousson.github.io/sharepointr/reference/sp_site.html) function to see if you're able to access the site at all.

If that works, try it with [get_sp_drive](https://elipousson.github.io/sharepointr/reference/sp_drive.html) and then [get_sp_item](https://elipousson.github.io/sharepointr/reference/get_sp_item.html). If that doesn't work, I'd love to see an example of the URLs you are using to try to figure out where the problem may be.

If you authenticated a request previously but it is no longer working, you may need to clear out the expired credentials. You can use `sharepointr::AzureR_config_ls()` to list any files in the expected configuration directory and then use `sharepointr::AzureR_config_delete()` to remove those files (resetting the authentication process).

If you want to get a recursive file list from a directory URL, you need the [sp_dir_info](https://elipousson.github.io/sharepointr/reference/sp_dir_info.html) function with recurse = TRUE (it defaults to FALSE). Similarly, if you want to download files in a directory and sub-directories, you need [download_sp_item](https://elipousson.github.io/sharepointr/reference/download_sp_item.html) with recursive = TRUE (it also defaults to FALSE).
