### ISSUE TITLE
Expand documentation for `write_sharepoint()` (esp. limits on `dest` argument)

### ISSUE THREAD

**Issue by VtheRtech** [elipousson/sharepointr#9]
How does the dest operator work? its somewhat unclear in documentation. Could you provide an example of how the whole function might work when using the dest operator?

**Comment by elipousson** [comment]
Thanks! Might take me a day or two to get to this but I can fill in some examples and explain when you might use one option or another. There is some duplication in the interface so I can see how it is a little confusing.

If you have [a reprex](https://reprex.tidyverse.org/) showing how you're trying to use it, that would also be welcome on my end.

**Comment by elipousson** [comment]
Hoping to double-check the docs and add some examples but here is a brief vignette https://elipousson.github.io/sharepointr/articles/read-write.html Feedback or questions are welcome.

**Comment by VtheRtech** [comment]
this input returns
``` R
drivelist <- sharepointr::list_sp_drives(docx_shared_url)
drv <-  drivelist[[5]][[3]]
str(drv)
id <-  drivelist[[3]][[3]]
print(id)


write_sharepoint(
  mtcars,
  file = "mtcars.csv",
  dest = file_shared_url,
  drive_name = drv
)
```
this ouput.
``` R 
+                             drive_name = drv,
+                             dest = file_shared_url)
Loading Microsoft Graph login for default tenant
Error: Invalid drive name
```
I'm really not sure why the drive name is not working when its directly retrieved from the list like this.

**Comment by elipousson** [comment]
Not sure I know the issue but I suspect the issue may be related to using a file URL as the destination rather than a folder URL. Getting the URL parsing to work consistently has been a little tricky so it is also possible this is a bug.

Can you try something like this? You'd need to substitute an actual folder URL for your SharePoint site for the placeholder, of course.

```{r}
library(sharepointr)

folder_url <- "<Folder URL>"

# This should work as is
write_sharepoint(
  mtcars,
  "mtcars.csv",
  dest = folder_url,
  overwrite = TRUE
)

# if you want to supply drive separately from the destination
# you can list drives
drive_list <- list_sp_drives(folder_url)

# And then subset a ms_drive object (e.g. the 3rd listed drive)
drive <- drive_list[["ms_drive"]][[3]]

# Or get the drive_id (e.g. the 3rd listed drive)
drive_id <- drive_list[["id"]][[3]]

# This should work (if it doesn't that is a bug)
write_sharepoint(
  mtcars,
  "mtcars.csv",
  dest = folder_url,
  drive = drive,
  overwrite = TRUE
)

# And this should also work (if it doesn't that is a bug)
write_sharepoint(
  mtcars,
  "mtcars.csv",
  dest = folder_url,
  drive_id = drive_id,
  overwrite = TRUE
)
```

**Comment by VtheRtech** [comment]
Wow, that worked thank you!

**Comment by VtheRtech** [comment]
Hi, 

I keep getting this error: 
```R
Error: 
! 'dest' must be single string, not an empty character vector. 
```

which is weird because I've been filling it out like so:  `dest = address` I tried also just putting the whole string in. This kinda odd that it stopped working when it was workig when you posted this.

**Comment by elipousson** [comment]
Can you share a reprex? Sounds like a URL parsing issue but difficult to diagnose without knowing what you're using as an input.

**Comment by VtheRtech** [comment]
I think your correct about the URL parsing issue when I copy the url directly from sharepoint. example: %20% instead of space, and with the tag at the end it, it doesn't seem to be having an issue. 

However that copying directly from sharepoint is not a good solution, URL needs to be in a format that doesnt expire. the odd thing is the generic way of writtiing urls works perfectly fine for read the function just not the write function.

**Comment by VtheRtech** [comment]
maybe adding something like `?file` at the end of the url would help?
